### ISSUE TITLE
ping.json

### ISSUE THREAD

**Issue by jsugarman** [ministryofjustice/laa-fee-calculator#40]
/ping.json endpoint returns 501 and 
```
{
build_date: null,
version_number: null,
build_tag: null,
commit_id: null
}
```

**Comment by ibrechin** [comment]
These are all based on environment variables which will need to be set on deployment, namely:
`APP_BUILD_DATE`
`APPVERSION`
`APP_BUILD_TAG`
`APP_GIT_COMMIT`
