### ISSUE TITLE
error response consistency

### ISSUE THREAD

**Issue by jsugarman** [ministryofjustice/laa-fee-calculator#48]
##### What
consistent error responses (or not) - to discuss

##### Why
While implementing some error handling in the client i have noticed that supplying `‘A STRING’` to the `scenario` param on endpoints like fee-types throws a 500, Django ValueError response (body), while supplying erroneous datatypes to, say, the `advocate_type` param on the same endpoint just responds with a 200, with empty results: []. In addition the fee-schemes endpoint will return, for example, a 400,  `[ "case_date should be in the format YYYY-MM-DD"]` 

- worth discussing a consistent approach and which would be the best.

**Comment by ibrechin** [comment]
@jsugarman is this one ok to close now?

**Comment by jsugarman** [comment]
yep, closing. cheers
