### ISSUE TITLE
AGFS scheme 9 (and 10) contempt issues

### ISSUE THREAD

**Issue by jsugarman** [ministryofjustice/laa-fee-calculator#52]
##### What 
The fee amounts for "contempt hearings" maybe half of what they should be

##### Why 
see [regs regarding contempt](http://www.legislation.gov.uk/uksi/2013/435/schedule/1/paragraph/21/made) . The amounts are based on a per day value but the unit for these are halfday - i.e. amounts would need halving and kept as half day or changed to day unit

**Comment by jsugarman** [comment]
From CCCDs point of view scheme 9 (and probably 10 too) contempt cases behave in this way:

1. there is no option for `Contempt (apportioned)`
2. Contempt fixed fee accepts a whole number only

<img width="813" alt="screen shot 2018-07-05 at 11 29 23" src="https://user-images.githubusercontent.com/7016425/42318613-786c5f64-8047-11e8-9605-a8eb639d7849.png">

**Comment by ibrechin** [comment]
Changed units of contempt fees and (committal fees which were also erroneously halfday) to day, as of https://github.com/ministryofjustice/laa-fee-calculator/pull/50

**Comment by jsugarman** [comment]
👍
